Лабораторная работа №4

Выполнила студентка группы 6131-010402D Фролова Анастасия Сергеевна

1:

Считать в pandas.DataFrame любой источник данных: CSV, JSON, Excel-файл, HTML-таблицу и т.п.

In [ ]:
import numpy as np
import pandas as pd

from pathlib import Path
from matplotlib import pyplot as plt

import sklearn as sk
import seaborn as sns

from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

2:

Датасет и подготовка данных:

Привести описание датасета.

In [ ]:
path = '...'

df = pd.read_csv(Path(path, 'healthcare-dataset-stroke-data.csv'))

Датасет содержит данные о пациентах. Эти данные используются для прогнозирования вероятности инсульта у пациента на основе таких входных параметров, как пол, возраст, различные заболевания и статус курения.
* id - уникальный идентификатор;
* gender - «Мужской», «Женский» или «Другой»;
* age - возраст пациента;
* hypertension - наличие или отсутствие гипертензии;
* heart_disease - наличие или отсутствие заболеваний сердца;
* ever_married - женат или нет;
* work_type - «Ребенок», «Госслужащий», «Безработный», «ИП» или «Самозанятый»;
* Residence_type - «Сельское» или «Городское»;
* avg_glucose_level - средний уровень глюкозы в крови;
* bmi - индекс массы тела;
* smoking_status - «ранее курил», «никогда не курил», «курящий» или «неизвестно»;
* stroke - наличие или отсутствие инсульта.

In [3]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

Осуществить предобработку данных (избавиться от null, убрать некоторые признаки и т.п.) - "подчистить данные".

In [4]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [5]:
# Избавляемся от NaN

df_no_NaN = df.dropna()
df_no_NaN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4909 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 4909 non-null   int64
 1   gender             4909 non-null   object
 2   age                4909 non-null   float64
 3   hypertension       4909 non-null   int64
 4   heart_disease      4909 non-null   int64
 5   ever_married       4909 non-null   object
 6   work_type          4909 non-null   object
 7   Residence_type     4909 non-null   object
 8   avg_glucose_level  4909 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     4909 non-null   object
 11  stroke             4909 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 498.6+ KB

Закодировать категориальные признаки при необходимости.

In [ ]:
cat_cols = ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status'] # Столбцы с категориальными признаками

In [ ]:
df_drop = pd.get_dummies(df_no_NaN, columns=cat_cols, drop_first=False) #OneHot Encoder
df_drop.head() # Проверяем, что кодирование прошло успешно

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,gender_Other,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,9046,67.0,0,1,228.69,36.6,1,False,True,False,...,False,True,False,False,False,True,False,True,False,False
2,31112,80.0,0,1,105.92,32.5,1,False,True,False,...,False,True,False,False,True,False,False,False,True,False
3,60182,49.0,0,0,171.23,34.4,1,True,False,False,...,False,True,False,False,False,True,False,False,False,True
4,1665,79.0,1,0,174.12,24.0,1,True,False,False,...,False,False,True,False,True,False,False,False,True,False
5,56669,81.0,0,0,186.21,29.0,1,False,True,False,...,False,True,False,False,False,True,False,True,False,False

In [ ]:
# После кодировки категориальных признаков столбцов стало значительно больше

print(df_drop.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4909 entries, 0 to 5109
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              4909 non-null   int64
 1   age                             4909 non-null   float64
 2   hypertension                    4909 non-null   int64
 3   heart_disease                   4909 non-null   int64
 4   avg_glucose_level               4909 non-null   float64
 5   bmi                             4909 non-null   float64
 6   stroke                          4909 non-null   int64
 7   gender_Female                   4909 non-null   bool
 8   gender_Male                     4909 non-null   bool
 9   gender_Other                    4909 non-null   bool
 10  ever_married_No                 4909 non-null   bool
 11  ever_married_Yes                4909 non-null   bool
 12  work_type_Govt_job              4909 non-null   bool
 13  work_type_Never_worked          4909 non-null   bool
 14  work_type_Private               4909 non-null   bool
 15  work_type_Self-employed         4909 non-null   bool
 16  work_type_children              4909 non-null   bool
 17  Residence_type_Rural            4909 non-null   bool
 18  Residence_type_Urban            4909 non-null   bool
 19  smoking_status_Unknown          4909 non-null   bool
 20  smoking_status_formerly smoked  4909 non-null   bool
 21  smoking_status_never smoked     4909 non-null   bool
 22  smoking_status_smokes           4909 non-null   bool
dtypes: bool(16), float64(3), int64(4)
memory usage: 383.5 KB
None

Нормализовать данные.

Разбить выборку на обучающую и тестовую.

In [10]:
# Выполним нормализацию и разбиение

X = df_drop.drop('stroke', axis=1)
y = df_drop['stroke']

scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(X)
X = pd.DataFrame(scaled_features, columns=X.columns)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 42, stratify=y)

3:

Дерево решений:

С использованием GridSearchCV осуществить подбор гиперпараметра DecisionTreeClassifier (как минимум max_depth, max_features, другие параметры - по желанию.)

In [11]:
grid = {
    'max_depth': range(1, X.shape[1]),
    'max_features': range(2, 20),
    'criterion': ['gini', 'entropy', 'log_loss'],
}

model_tree = DecisionTreeClassifier()

search = GridSearchCV(model_tree, grid, cv = 5, n_jobs= -1, verbose = 2)
search.fit(x_train, y_train)

Fitting 5 folds for each of 1134 candidates, totalling 5670 fits

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': range(1, 22),
                         'max_features': range(2, 20)},
             verbose=2)

In [12]:
search.best_params_

{'criterion': 'log_loss', 'max_depth': 3, 'max_features': 3}

In [13]:
best_model = search.best_estimator_
best_model_pred = best_model.predict(x_train)

In [14]:
print(f"Accuracy: {accuracy_score(y_train, best_model_pred)}; Precision: {precision_score(y_train, best_model_pred, average='weighted', zero_division=0)}; Recall: {recall_score(y_train, best_model_pred, average='weighted')}; F1_score: {f1_score(y_train, best_model_pred, average='weighted')}")

Accuracy: 0.9575087310826542; Precision: 0.9168229700995147; Recall: 0.9575087310826542; F1_score: 0.9367242715616809

In [15]:
print(f"Classification Report:")
print(classification_report(y_train, best_model_pred, zero_division=0))

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      3290
           1       0.00      0.00      0.00       146

    accuracy                           0.96      3436
   macro avg       0.48      0.50      0.49      3436
weighted avg       0.92      0.96      0.94      3436

Осуществить фильтрацию признаков (по какому-нибудь значению порога важности признака).

In [16]:
# Выводим feature_importance и сортируем с последующей фильтрацией

print(f"Most important features:")

features = zip(x_train.columns, best_model.feature_importances_)
features = sorted(features, key=lambda x: x[1], reverse=True)
for f_name, f_imp in features:
    if f_imp >= 0.01:
        print(f"Feature {f_name} with contribution {f_imp:.3f}")

Most important features:
Feature age with contribution 0.601
Feature work_type_children with contribution 0.260
Feature ever_married_No with contribution 0.095
Feature avg_glucose_level with contribution 0.044

Подобрать лучшую модель с использованием GridSearchCV на обучающей выборке с отфильтрованными признаками.

In [ ]:
# Выбираем 2 признака, так как его важность превосходит остальные

selected_features = ['age', 'work_type_children']
x_train_filtered = x_train[selected_features]

search_filtered = GridSearchCV(model_tree, grid, cv = 5, n_jobs= -1, verbose= 2)
search_filtered.fit(x_train_filtered, y_train)

Fitting 5 folds for each of 1134 candidates, totalling 5670 fits

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': range(1, 22),
                         'max_features': range(2, 20)},
             verbose=2)

In [19]:
search_filtered.best_params_

{'criterion': 'gini', 'max_depth': 1, 'max_features': 2}

In [20]:
best_model_filter = search_filtered.best_estimator_
best_model_filter_pred = best_model_filter.predict(x_train_filtered)

In [21]:
print(f"Accuracy: {accuracy_score(y_train, best_model_filter_pred)}; Precision: {precision_score(y_train, best_model_filter_pred, average='weighted', zero_division=0)}; Recall: {recall_score(y_train, best_model_filter_pred, average='weighted')}; F1_score: {f1_score(y_train, best_model_filter_pred, average='weighted')}")

Accuracy: 0.9575087310826542; Precision: 0.9168229700995147; Recall: 0.9575087310826542; F1_score: 0.9367242715616809

In [22]:
print(f"Classification Report:")
print(classification_report(y_train, best_model_filter_pred, zero_division=0))

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      3290
           1       0.00      0.00      0.00       146

    accuracy                           0.96      3436
   macro avg       0.48      0.50      0.49      3436
weighted avg       0.92      0.96      0.94      3436

Сравнить метрики до и после фильтрации признаков лучших моделей.

In [56]:
print("Before filter:")
print('Accuracy: {:.4f}'.format(accuracy_score(y_train, best_model_pred)))
print('Precision: {:.4f}'.format(precision_score(y_train, best_model_pred, average='weighted', zero_division=0)))
print('Recall: {:.4f}'.format(recall_score(y_train, best_model_pred, average='weighted', zero_division=0)))
print('F1-score: {:.4f}'.format(f1_score(y_train, best_model_pred, average='weighted', zero_division=0)))
print("----------------------------------------------------")
print("After filter:")
print('Accuracy: {:.4f}'.format(accuracy_score(y_train, best_model_filter_pred)))
print('Precision: {:.4f}'.format(precision_score(y_train, best_model_filter_pred, average='weighted', zero_division=0)))
print('Recall: {:.4f}'.format(recall_score(y_train, best_model_filter_pred, average='weighted', zero_division=0)))
print('F1-score: {:.4f}'.format(f1_score(y_train, best_model_filter_pred, average='weighted', zero_division=0)))

Before filter:
Accuracy: 0.9575
Precision: 0.9168
Recall: 0.9575
F1-score: 0.9367
----------------------------------------------------
After filter:
Accuracy: 0.9575
Precision: 0.9168
Recall: 0.9575
F1-score: 0.9367

In [ ]:
# После фильтрации признаков метрики не изменились, но важно заметить, что расчеты проходят значительно быстрее, ведь мы используем лишь два признака

4:

Случайный лес

Построить случайный лес (RandomForestClassifier), c использованием GridSearchCV осуществить подбор гиперпараметра.

In [23]:
grid_rand = {
    'max_depth': range(1, X.shape[1]),
    'n_estimators': range(10, 30, 10),
    'criterion': ['gini', 'entropy', 'log_loss']
}

model_rand_tree = RandomForestClassifier()

search_rt = GridSearchCV(model_rand_tree, grid_rand, cv = 5, n_jobs= -1, verbose = 2)
search_rt.fit(x_train, y_train)

Fitting 5 folds for each of 126 candidates, totalling 630 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': range(1, 22),
                         'n_estimators': range(10, 30, 10)},
             verbose=2)

In [24]:
search_rt.best_params_

{'criterion': 'entropy', 'max_depth': 11, 'n_estimators': 10}

In [25]:
best_model_rt = search_rt.best_estimator_
best_model_pred_rt = best_model_rt.predict(x_train)

In [26]:
print(f"Accuracy: {accuracy_score(y_train, best_model_pred)}; Precision: {precision_score(y_train, best_model_pred_rt, average='weighted', zero_division=0)}; Recall: {recall_score(y_train, best_model_pred_rt, average='weighted')}; F1_score: {f1_score(y_train, best_model_pred_rt, average='weighted')}")

Accuracy: 0.9575087310826542; Precision: 0.9772698224075335; Recall: 0.9767171129220024; F1_score: 0.9724639525197436

Осуществить фильтрацию признаков.

In [27]:
# Выводим feature_importance и сортируем с последующей фильтрацией

print(f"Most important features:")

features_rt = zip(x_train.columns, best_model_rt.feature_importances_)
features_rt = sorted(features_rt, key=lambda x: x[1], reverse=True)
for f_name, f_imp in features_rt:
    if f_imp >= 0.1:
        print(f"Feature {f_name} with contribution {f_imp}")

Most important features:
Feature age with contribution 0.26183748510980054
Feature avg_glucose_level with contribution 0.1710838473082535
Feature bmi with contribution 0.13825944141550334
Feature id with contribution 0.13428281844169615

Подобрать лучшую модель с использованием GridSearchCV на обучающей выборке с отфильтрованными признаками.

In [28]:
# Выбираем 4 первых признака

selected_features_rt = ['age', 'avg_glucose_level', 'id', 'bmi']
x_train_filtered_rt = x_train[selected_features_rt]

search_filtered_rt = GridSearchCV(model_rand_tree, grid_rand, cv = 5, n_jobs= -1, verbose= 2)
search_filtered_rt.fit(x_train_filtered_rt, y_train)

Fitting 5 folds for each of 126 candidates, totalling 630 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': range(1, 22),
                         'n_estimators': range(10, 30, 10)},
             verbose=2)

In [29]:
search_filtered_rt.best_params_

{'criterion': 'gini', 'max_depth': 1, 'n_estimators': 10}

In [30]:
best_model_filter_rt = search_filtered_rt.best_estimator_
best_model_filter_pred_rt = best_model_filter_rt.predict(x_train_filtered_rt)

In [31]:
print(f"Accuracy: {accuracy_score(y_train, best_model_filter_pred_rt)}; Precision: {precision_score(y_train, best_model_filter_pred_rt, average='weighted', zero_division=0)}; Recall: {recall_score(y_train, best_model_filter_pred_rt, average='weighted')}; F1_score: {f1_score(y_train, best_model_filter_pred_rt, average='weighted')}")

Accuracy: 0.9575087310826542; Precision: 0.9168229700995147; Recall: 0.9575087310826542; F1_score: 0.9367242715616809

Сравнить метрики до и после фильтрации признаков лучших моделей.

In [57]:
print("Before filter:")
print('Accuracy: {:.4f}'.format(accuracy_score(y_train, best_model_pred_rt)))
print('Precision: {:.4f}'.format(precision_score(y_train, best_model_pred_rt, average='weighted', zero_division=0)))
print('Recall: {:.4f}'.format(recall_score(y_train, best_model_pred_rt, average='weighted', zero_division=0)))
print('F1-score: {:.4f}'.format(f1_score(y_train, best_model_pred_rt, average='weighted', zero_division=0)))
print("----------------------------------------------------")
print("After filter:")
print('Accuracy: {:.4f}'.format(accuracy_score(y_train, best_model_filter_pred_rt)))
print('Precision: {:.4f}'.format(precision_score(y_train, best_model_filter_pred_rt, average='weighted', zero_division=0)))
print('Recall: {:.4f}'.format(recall_score(y_train, best_model_filter_pred_rt, average='weighted', zero_division=0)))
print('F1-score: {:.4f}'.format(f1_score(y_train, best_model_filter_pred_rt, average='weighted', zero_division=0)))

Before filter:
Accuracy: 0.9767
Precision: 0.9773
Recall: 0.9767
F1-score: 0.9725
----------------------------------------------------
After filter:
Accuracy: 0.9575
Precision: 0.9168
Recall: 0.9575
F1-score: 0.9367

In [ ]:
# Точность и остальные метрики ухудшились, что говорит о том, что в результате фильтрации и дальнейшего исключения признаков была сокращена важная информация для классификации

5:

Метод ближайших соседей:

С использованием GridSearchCV осуществить подбор гиперпараметра KNeighborsClassifier (n_neighbors).

In [32]:
grid_knn = {
    'n_neighbors': range(2, 20)
}

model_knn = KNeighborsClassifier()

search_knn = GridSearchCV(model_knn, grid_knn, cv = 5, n_jobs= -1, verbose = 2)
search_knn.fit(x_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': range(2, 20)}, verbose=2)

In [33]:
search_knn.best_params_

{'n_neighbors': 6}

In [34]:
best_model_knn = search_knn.best_estimator_
best_model_pred_knn = best_model_rt.predict(x_train)

In [35]:
print(f"Accuracy: {accuracy_score(y_train, best_model_pred_knn)}; Precision: {precision_score(y_train, best_model_pred_knn, average='weighted', zero_division=0)}; Recall: {recall_score(y_train, best_model_pred_knn, average='weighted')}; F1_score: {f1_score(y_train, best_model_pred_knn, average='weighted')}")

Accuracy: 0.9767171129220024; Precision: 0.9772698224075335; Recall: 0.9767171129220024; F1_score: 0.9724639525197436

Осуществить фильтрацию признаков.

In [36]:
# Для метода ближайших соседей нет feature_importances_, поэтому выберем из предыдущих моделей набор отфильтрованных признаков (был выбран набор из дерева решений)

x_train_filtered_knn = x_train_filtered_rt
x_train_filtered_knn.head()

           age  avg_glucose_level        id       bmi
506   0.633789           0.888976  0.935976  0.284078
1408  0.021973           0.260964  0.018226  0.068729
798   0.853516           0.205337  0.392572  0.274914
4131  0.548340           0.253809  0.288075  0.235968
1217  0.377441           0.208983  0.358138  0.305842

Подобрать лучшую модель с использованием GridSearchCV на обучающей выборке с отфильтрованными признаками.

In [37]:
search_filtered_knn = GridSearchCV(model_knn, grid_knn, cv = 5, n_jobs= -1, verbose= 2)
search_filtered_knn.fit(x_train_filtered_knn, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': range(2, 20)}, verbose=2)

In [38]:
search_filtered_knn.best_params_

{'n_neighbors': 10}

In [39]:
best_model_filter_knn = search_filtered_knn.best_estimator_
best_model_filter_pred_knn = best_model_filter_knn.predict(x_train_filtered_knn)

In [40]:
print(f"Accuracy: {accuracy_score(y_train, best_model_filter_pred_knn)}; Precision: {precision_score(y_train, best_model_filter_pred_knn, average='weighted', zero_division=0)}; Recall: {recall_score(y_train, best_model_filter_pred_knn, average='weighted')}; F1_score: {f1_score(y_train, best_model_filter_pred_knn, average='weighted')}")

Accuracy: 0.9577997671711292; Precision: 0.9595811452672534; Recall: 0.9577997671711292; F1_score: 0.9374416739184648

Сравнить метрики до и после фильтрации признаков.

In [58]:
print("Before filter:")
print('Accuracy: {:.4f}'.format(accuracy_score(y_train, best_model_pred_knn)))
print('Precision: {:.4f}'.format(precision_score(y_train, best_model_pred_knn, average='weighted', zero_division=0)))
print('Recall: {:.4f}'.format(recall_score(y_train, best_model_pred_knn, average='weighted', zero_division=0)))
print('F1-score: {:.4f}'.format(f1_score(y_train, best_model_pred_knn, average='weighted', zero_division=0)))
print("----------------------------------------------------")
print("After filter:")
print('Accuracy: {:.4f}'.format(accuracy_score(y_train, best_model_filter_pred_knn)))
print('Precision: {:.4f}'.format(precision_score(y_train, best_model_filter_pred_knn, average='weighted', zero_division=0)))
print('Recall: {:.4f}'.format(recall_score(y_train, best_model_filter_pred_knn, average='weighted', zero_division=0)))
print('F1-score: {:.4f}'.format(f1_score(y_train, best_model_filter_pred_knn, average='weighted', zero_division=0)))

Before filter:
Accuracy: 0.9767
Precision: 0.9773
Recall: 0.9767
F1-score: 0.9725
----------------------------------------------------
After filter:
Accuracy: 0.9578
Precision: 0.9596
Recall: 0.9578
F1-score: 0.9374

In [ ]:
# В данном случае использование меньше набора признаков привело к ухудшению результатов точности и метрик precision, recall, f1

6:

Если наблюдается улучшение метрик после фильтрации признаков хотя бы для одной из моделей, то для набора отфильтрованных признаков (пересечение множеств отфильтрованных признаков каждой модели или объединение множеств – не особо важно, главное описать, каким образом получен новый subset данных) заново построить наилучшие модели KNeighborsClassifier, DecisionTreeClassifier, RandomForestClassifier, сравнить модели в пункте 7 на одинаковом полученном наборе отфильтрованных признаков. Иначе – пропустить этот пункт.

In [53]:
# Улучшения метрик после фитральции не наблюдалось, была лишь незначительная разница в точности для модели обычного древа решений
# В случае остальных методов классификации значения метрик лишь ухудшались

7:

Оценка качества построенных моделей:

In [54]:

from sklearn.tree import export_graphviz

Визуализировать любое полученное дерево решений.

In [ ]:
# Вписать свой путь

data_path = "..."

# Используем .dot формат для визуализации дерева
export_graphviz(
    best_model,
    feature_names=x_train.columns,
    class_names=['Stroke','No stroke'],
    out_file = f'{data_path}/small_tree.dot',
    filled = True
)

!dot -Tpng ./images/small_tree.dot -o ./images/small_tree.png

Сравнить лучшие модели KNeighborsClassifier, DecisionTreeClassifier, RandomForestClassifier на тестовой выборке. Привести значения метрик

In [59]:
print("DecisionTreeClassifier:")
print(f"Accuracy: {accuracy_score(y_test, best_model.predict(x_test)):.3f}")
print(f"Precision: {precision_score(y_test, best_model.predict(x_test), average='weighted', zero_division=0):.3f}")
print(f"Recall: {recall_score(y_test, best_model.predict(x_test), average='weighted', zero_division=0):.3f}")
print(f"F1_score: {f1_score(y_test, best_model.predict(x_test), average='weighted', zero_division=0):.3f}")
print("----------------------------------------------------")

print("RandomForestClassifier:")
print(f"Accuracy: {accuracy_score(y_test, best_model_rt.predict(x_test)):.3f}")
print(f"Precision: {precision_score(y_test, best_model_rt.predict(x_test), average='weighted', zero_division=0):.3f}")
print(f"Recall: {recall_score(y_test, best_model_rt.predict(x_test), average='weighted', zero_division=0):.3f}")
print(f"F1_score: {f1_score(y_test, best_model_rt.predict(x_test), average='weighted', zero_division=0):.3f}")
print("----------------------------------------------------")

print("KNeighborsClassifier:")
print(f"Accuracy: {accuracy_score(y_test, best_model_knn.predict(x_test)):.3f}")
print(f"Precision: {precision_score(y_test, best_model_knn.predict(x_test), average='weighted', zero_division=0):.3f}")
print(f"Recall: {recall_score(y_test, best_model_knn.predict(x_test), average='weighted', zero_division=0):.3f}")
print(f"F1_score: {f1_score(y_test, best_model_knn.predict(x_test), average='weighted', zero_division=0):.3f}")

DecisionTreeClassifier:
Accuracy: 0.957
Precision: 0.916
Recall: 0.957
F1_score: 0.936
----------------------------------------------------
RandomForestClassifier:
Accuracy: 0.955
Precision: 0.925
Recall: 0.955
F1_score: 0.937
----------------------------------------------------
KNeighborsClassifier:
Accuracy: 0.957
Precision: 0.916
Recall: 0.957
F1_score: 0.936

In [ ]:
# Лучшие результаты на тестовой выборке показывают модель дерева решений и метод ближайших соседей